# Generated by Django 5.0.1 on 2024-03-20 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0003_remove_post_header_image_post_file_upload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='file_upload',
            new_name='header_image',
        ),
    ]
